'use strict';

/**
fancy terminal UI — the pretty progress bars and stuff you see while analyzing

has a sticky footer that stays at the bottom while logs scroll above it
uses ANSI codes to move cursor around and redraw,,, its complicated
also shows a spinner cuz everyone loves spinners
 */

const ESC = '\x1B[';

// ANSI color helpers — more magic escape sequences
// i just copy-pasted these from prompt.js cuz they work
const c = {
  pink: (str) => `${ESC}38;5;206m${str}${ESC}0m`,
  dim: (str) => `${ESC}2m${str}${ESC}0m`,
  green: (str) => `${ESC}32m${str}${ESC}0m`,
  red: (str) => `${ESC}31m${str}${ESC}0m`,
  yellow: (str) => `${ESC}33m${str}${ESC}0m`,
  cyan: (str) => `${ESC}36m${str}${ESC}0m`,
  bold: (str) => `${ESC}1m${str}${ESC}0m`,
};

// box drawing characters — those fancy corners and lines
// cuz plain ASCII boxes are for peasants
const box = {
  tl: '╭', tr: '╮', bl: '╰', br: '╯',
  h: '─', v: '│',
  sepL: '├', sepR: '┤', sepM: '┼', sepT: '┬', sepB: '┴'
};

// the ascii art logo — generated by some online tool i think
// looks cool tho
const LOGO = [
  "  ____                                     ",
  " |  _ \\ ___ _ __   ___  _ __ ___  ___  ___ ",
  " | |_) / _ \\ '_ \\ / _ \\| '__/ _ \\/ __|/ _ \\",
  " |  _ <  __/ |_) | (_) | | | (_) \\__ \\  __/",
  " |_| \\_\\___| .__/ \\___/|_|  \\___/|___/\\___|",
  "           |_|                             "
];

// braille spinner frames — looks fancy while waiting
// cycles through these to make the little animation
const SPINNER_FRAMES = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];
let _spinnerTick = 0;
let _spinnerTimer = null;

// state variables — tracking what mode were in and stuff
let _mode = null;  // 'analyze', 'serve', or null
let _isCI = process.env.CI || !process.stdout.isTTY;
let _stats = { filesFound: 0, filesAnalyzed: 0, currentFile: '' };
let _liveAiText = '';
let _lastRenderLines = 0;

// serve mode keeps track of server info and recent logs
let _serveInfo = { url: '', mapPath: '' };
let _serveLogs = [];


function isCI() { return _isCI; }
function setCI(value) { _isCI = value; }

function clearLine() { process.stdout.write(ESC + '2K'); }
function moveUp(n = 1) { if (n > 0) process.stdout.write(ESC + n + 'A'); }
function moveToStart() { process.stdout.write('\r'); }
function hideCursor() { if (!_isCI) process.stdout.write(ESC + '?25l'); }
function showCursor() { if (!_isCI) process.stdout.write(ESC + '?25h'); }

function getWidth() {
  const w = (process.stdout.columns || 80) - 1;
  return Math.min(Math.max(w, 64), 110);
}

function truncate(str, maxLen) {
  if (str.length <= maxLen) return str;
  return '...' + str.slice(str.length - (maxLen - 3));
}

function getProgressBar(percent, width = 40) {
  const filled = Math.round((width * percent) / 100);
  const empty = width - filled;
  return c.pink('█'.repeat(filled)) + c.dim('░'.repeat(empty));
}

function stripAnsi(str) {
  return str.replace(/\x1B\[\d+;?\d*;?\d*m/g, '');
}

function centerText(text, width) {
  const plain = stripAnsi(text);
  const pad = Math.max(0, width - plain.length);
  const left = Math.floor(pad / 2);
  const right = pad - left;
  return ' '.repeat(left) + text + ' '.repeat(right);
}

function padRight(text, width) {
  const plain = stripAnsi(text);
  return text + ' '.repeat(Math.max(0, width - plain.length));
}

// clears the sticky UI so we can print a log line
// moves cursor up and erases lines,,, terminal wizardry
function clearUI() {
  if (_lastRenderLines > 0) {
    moveToStart();
    clearLine();
    for (let i = 1; i < _lastRenderLines; i++) {
      moveUp(1);
      clearLine();
    }
    _lastRenderLines = 0;
  }
}

// renders the analyze mode UI — progress bar, stats, logo, live AI preview
// returns a big string with newlines that gets printed
function renderAnalyzeUI() {
  const width = getWidth();
  const innerW = width - 2;
  const lines = [];

  // Top border
  lines.push(c.dim(box.tl + box.h.repeat(innerW) + box.tr));

  // 1. Progress Bar
  const totalFiles = _stats.filesSummarizable || _stats.filesFound || 1;
  const percent = Math.round((_stats.filesAnalyzed / totalFiles) * 100);
  const barWidth = Math.max(10, Math.floor(innerW * 0.4));
  const bar = getProgressBar(percent, barWidth);
  const progText = `${percent}% ▕${bar}▏ ${_stats.filesAnalyzed}/${totalFiles}`;
  lines.push(c.dim(box.v) + centerText(progText, innerW) + c.dim(box.v));
  
  lines.push(c.dim(box.sepL + box.h.repeat(innerW) + box.sepR));

  // 2. Table (Stats & Current File)
  const colW = Math.floor((innerW - 1) / 2);
  const foundStr = ` Files Found:    ${_stats.filesFound}`;
  const analyzedStr = ` Summarized:     ${_stats.filesAnalyzed}/${_stats.filesSummarizable || _stats.filesFound}`;
  const modelStr = ` Model:          ${truncate(_stats.modelLabel || 'N/A', colW - 18)}`;
  
  const leftStr1 = padRight(foundStr, colW);
  const leftStr2 = padRight(analyzedStr, colW);
  const leftStr3 = padRight(modelStr, colW);

  let fileStr = _stats.currentFile || '...';
  const maxFileLen = innerW - colW - 18; 
  fileStr = truncate(fileStr, maxFileLen > 10 ? maxFileLen : 10);
  
  const spinner = c.cyan(SPINNER_FRAMES[_spinnerTick % SPINNER_FRAMES.length]);
  const rightStr1 = padRight(` Current: ${spinner} ${fileStr}`, innerW - colW - 1);
  const rightStr2 = padRight('', innerW - colW - 1);
  const rightStr3 = padRight('', innerW - colW - 1);
  
  lines.push(c.dim(box.v) + leftStr1 + c.dim(box.v) + rightStr1 + c.dim(box.v));
  lines.push(c.dim(box.v) + leftStr2 + c.dim(box.v) + rightStr2 + c.dim(box.v));
  lines.push(c.dim(box.v) + leftStr3 + c.dim(box.v) + rightStr3 + c.dim(box.v));
  
  // 3. Live AI Preview (Always present to keep height constant)
  lines.push(c.dim(box.sepL + box.h.repeat(innerW) + box.sepR));
  const previewText = truncate(stripAnsi(_liveAiText ? _liveAiText.replace(/\n/g, ' ') : 'Waiting for AI...'), innerW - 13);
  lines.push(c.dim(box.v) + padRight('  ' + c.pink('Live AI: ') + (_liveAiText ? c.dim(previewText) : c.dim(previewText)), innerW) + c.dim(box.v));

  lines.push(c.dim(box.sepL + box.h.repeat(innerW) + box.sepR));

  // 4. Logo
  for (const row of LOGO) {
    lines.push(c.dim(box.v) + c.pink(centerText(row, innerW)) + c.dim(box.v));
  }

  // Bottom border
  lines.push(c.dim(box.bl + box.h.repeat(innerW) + box.br));

  return lines.join('\n');
}

// renders the serve mode UI — logo, URL, recent logs
function renderServeUI() {
  const width = getWidth();
  const innerW = width - 2;
  const lines = [];

  // Top border
  lines.push(c.dim(box.tl + box.h.repeat(innerW) + box.tr));

  // Logo
  for (const row of LOGO) {
    lines.push(c.dim(box.v) + c.pink(centerText(row, innerW)) + c.dim(box.v));
  }

  // Info
  lines.push(c.dim(box.sepL + box.h.repeat(innerW) + box.sepR));
  const urlStr = c.green(`✓ Server running at `) + c.bold(_serveInfo.url);
  const mapStr = c.dim(`  Map: ${_serveInfo.mapPath}`);
  lines.push(c.dim(box.v) + padRight(urlStr, innerW) + c.dim(box.v));
  lines.push(c.dim(box.v) + padRight(mapStr, innerW) + c.dim(box.v));
  lines.push(c.dim(box.sepL + box.h.repeat(innerW) + box.sepR));

  // Logs
  lines.push(c.dim(box.v) + centerText('RECENT REQUESTS', innerW) + c.dim(box.v));
  const recentLogs = _serveLogs.slice(-7);
  while (recentLogs.length < 7) recentLogs.push('');
  for (const logItem of recentLogs) {
    const cleanLog = truncate(logItem, innerW - 4);
    lines.push(c.dim(box.v) + padRight('  ' + cleanLog, innerW) + c.dim(box.v));
  }

  // Bottom border
  lines.push(c.dim(box.bl + box.h.repeat(innerW) + box.br));

  return lines.join('\n');
}

function renderUI() {
  if (_mode === 'analyze') return renderAnalyzeUI();
  if (_mode === 'serve') return renderServeUI();
  return '';
}

function redraw() {
  if (_isCI || !_mode) return;
  
  const newRender = renderUI();
  const newLines = newRender.split('\n');
  
  if (_lastRenderLines > 0) {
    // In-place update
    moveUp(_lastRenderLines - 1);
    
    for (let i = 0; i < newLines.length; i++) {
      if (i > 0) process.stdout.write('\n');
      moveToStart();
      clearLine();
      process.stdout.write(newLines[i]);
    }
    
    // Clear any leftover lines if new height is smaller
    if (_lastRenderLines > newLines.length) {
      const diff = _lastRenderLines - newLines.length;
      for (let i = 0; i < diff; i++) {
        process.stdout.write('\n');
        moveToStart();
        clearLine();
      }
      moveUp(diff); // go back to the bottom of the current UI
    }
  } else {
    // Fresh print (e.g. after clearUI or initial start)
    // Create empty space first to prevent terminal from scrolling DURING the print
    process.stdout.write('\n'.repeat(newLines.length));
    moveUp(newLines.length);

    for (let i = 0; i < newLines.length; i++) {
      if (i > 0) process.stdout.write('\n');
      process.stdout.write(newLines[i]);
    }
  }
  
  _lastRenderLines = newLines.length;
}

function start() {
  if (_mode === 'analyze') return;
  _mode = 'analyze';
  _stats = { filesFound: 0, filesAnalyzed: 0, currentFile: '' };
  _liveAiText = '';
  
  if (!_isCI) {
    hideCursor();
    _lastRenderLines = 0;
    redraw();
    
    if (_spinnerTimer) clearInterval(_spinnerTimer);
    _spinnerTimer = setInterval(() => {
      _spinnerTick++;
      if (_mode === 'analyze') redraw();
    }, 100);
  }
}

function startServe(url, mapPath) {
  if (_mode === 'serve') return;
  _mode = 'serve';
  _serveInfo = { url, mapPath: truncate(mapPath, 60) };
  _serveLogs = [];
  
  if (!_isCI) {
    hideCursor();
    _lastRenderLines = 0;
    redraw();
  } else {
    console.log(`[reporose-server] Server listening on ${url}`);
    console.log(`[reporose-server] Serving map from ${mapPath}`);
  }
}

function stop() {
  if (!_mode) return;
  _mode = null;
  if (_spinnerTimer) {
    clearInterval(_spinnerTimer);
    _spinnerTimer = null;
  }
  showCursor();
  process.stdout.write('\n');
}

// filters out spammy progress messages so they dont clutter the UI
// cuz nobody wants to see "50% ██████░░░░" 100 times
// this is regex,,,,,, I really need to learn this shit,, this is powerfull
function isSpammyLog(msg) {
  const s = stripAnsi(msg);
  return /^\d+%/.test(s) || 
         /\[=*>*\s*\]/.test(s) || 
         /░/.test(s) || 
         /█/.test(s) || 
         /Scanned \d+ files/.test(s) ||
         /Summarizing\s+\d+\s+files/.test(s);
}

function log(message) {
  if (!_mode || _isCI) {
    // no fancy UI, just print it
    console.log(`[reporose] ${message}`);
    return;
  }

  if (_mode === 'analyze') {
    // clear UI, print log, redraw UI
    if (!isSpammyLog(message)) {
      clearUI();
      console.log(c.pink(' ➜ ') + c.dim('log: ') + message);
      redraw();
    }
  } else if (_mode === 'serve') {
    // add to log buffer and redraw
    _serveLogs.push(message);
    if (_serveLogs.length > 20) _serveLogs.shift();
    redraw();
  }
}

function warn(message) {
  if (_mode === 'analyze' && !_isCI) {
    clearUI();
    console.log(c.yellow(' ⚠ ') + c.dim('warn: ') + message);
    redraw();
  } else {
    log(c.yellow(`⚠ ${message}`));
  }
}

function error(message) {
  if (_mode === 'analyze' && !_isCI) {
    clearUI();
    console.log(c.red(' ✗ ') + c.dim('error: ') + message);
    redraw();
  } else {
    log(c.red(`✗ ${message}`));
  }
}

function done(message) {
  if (_mode === 'analyze' && !_isCI && message) {
    clearUI();
    console.log(c.green(' ✓ ') + c.dim('done: ') + message);
    redraw(); // Keep final UI on screen
  } else if (message && _mode !== 'serve') {
    log(c.green(`✓ ${message}`));
  }
  stop();
}

function serveLog(method, url) {
  const methodColor = method === 'GET' ? c.green(method) : c.pink(method);
  log(`→ ${methodColor} ${c.dim(url)}`);
}

function serveError(method, url, errMessage) {
  const methodColor = method === 'GET' ? c.green(method) : c.pink(method);
  log(c.red(`✗ ${methodColor} ${c.dim(url)} - ${errMessage}`));
}

function updateStats(stats) {
  if (_mode !== 'analyze') return;
  _stats = { ..._stats, ...stats };
  if (!_isCI) redraw();
}

function updateProgress(textOrObj) {
  if (_mode !== 'analyze') return;

  if (typeof textOrObj === 'object') {
    // update stats and maybe log
    _stats = { ..._stats, ...textOrObj };
    if (textOrObj.text && !isSpammyLog(textOrObj.text)) {
      log(textOrObj.text);
    } else if (!_isCI) {
      redraw();
    }
    return;
  }

  // parse progress text to extract numbers and filenames
  const text = textOrObj;
  const match = text.match(/(\d+)\/(\d+)/);
  if (match) {
    _stats.filesAnalyzed = parseInt(match[1], 10);
  }

  const processingMatch = text.match(/Processing\s+([^\s\(]+)/);
  if (processingMatch) {
    _stats.currentFile = processingMatch[1];
  } else {
    const fileMatch = text.match(/\d+\/\d+\s+(.+)$/);
    if (fileMatch) {
      _stats.currentFile = fileMatch[1];
    }
  }

  if (_isCI) {
    console.log(`[reporose] ${text}`);
  } else {
    redraw();
  }
}

function updateLiveAi(text) {
  if (_mode !== 'analyze') return;
  _liveAiText = text;
  if (!_isCI) redraw();
}

module.exports = {
  start,
  startServe,
  stop,
  log,
  warn,
  error,
  serveLog,
  serveError,
  updateProgress,
  updateStats,
  updateLiveAi,
  setLiveAI: updateLiveAi,
  done,
  isCI,
  setCI,
  isSpammyLog,
};
