'use strict';

/**
MCP Server for Reporose

well
All this is generated by AI
I dont know most of it,, but ill try my best to explain it

MCP = Model Context Protocol
its a way for AI assistants to talk to this server
and use reporose features through a standardized protocol

run it with: reporose mcp

then AI tools can call these methods to analyze repos and stuff
 */

// MCP SDK imports — these come from the official modelcontextprotocol package
// Server = the main server class
// StdioServerTransport = communicates over stdin/stdout (how MCP usually works)
// the schemas are for type validation i think
const { Server } = require('@modelcontextprotocol/sdk/server/index.js');
const { StdioServerTransport } = require('@modelcontextprotocol/sdk/server/stdio.js');
const {
  CallToolRequestSchema,
  ListResourcesRequestSchema,
  ListToolsRequestSchema,
  ReadResourceRequestSchema,
} = require('@modelcontextprotocol/sdk/types.js');

// regular node modules + reporose core modules
// scan = phase 1 (file scanning)
// mapDependencies = phase 2 (dependency mapping)
const fs = require('fs');
const path = require('path');
const { scan } = require('../core/scanner');
const { mapDependencies } = require('../core/mapper');
const { loadConfig } = require('../ai/config');

// creates and starts the MCP server
// sets up handlers for resources (files AI can read) and tools (functions AI can call)
async function startMcpServer(repoPath, options = {}) {
  // create the MCP server instance
  // tells the client (AI) what we can do: resources and tools
  const server = new Server(
    { name: 'reporose', version: '0.1.0' },
    { capabilities: { resources: {}, tools: {} } }
  );

  // figure out where the repo is and where map.json lives
  const targetPath = path.resolve(repoPath || process.cwd());
  const outDir = options.outDir || '.reporose';
  const mapPath = path.join(targetPath, outDir, 'map.json');

  // try to load existing map.json if its there
  let map = null;
  if (fs.existsSync(mapPath)) {
    map = JSON.parse(fs.readFileSync(mapPath, 'utf8'));
  }

  // handler: "what resources do you have?"
  // resources are like files AI can read directly
  // we expose map.json and AGENTS.md
  server.setRequestHandler(ListResourcesRequestSchema, async () => ({
    resources: [
      {
        uri: `reporose://${targetPath}/map.json`,
        mimeType: 'application/json',
        name: 'Repository Map',
        description: 'Full dependency map and file descriptions',
      },
      {
        uri: `reporose://${targetPath}/AGENTS.md`,
        mimeType: 'text/markdown',
        name: 'Project Context',
        description: 'AI agent instructions and project overview',
      },
    ],
  }));

  // handler: "read this resource for me"
  // actually returns the content of map.json or AGENTS.md
  server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
    const uri = request.params.uri;

    if (uri.endsWith('/map.json') && fs.existsSync(mapPath)) {
      const content = fs.readFileSync(mapPath, 'utf8');
      return {
        contents: [
          {
            uri,
            mimeType: 'application/json',
            text: content,
          },
        ],
      };
    }

    if (uri.endsWith('/AGENTS.md')) {
      const agentsPath = path.join(targetPath, 'AGENTS.md');
      if (fs.existsSync(agentsPath)) {
        const content = fs.readFileSync(agentsPath, 'utf8');
        return {
          contents: [
            {
              uri,
              mimeType: 'text/markdown',
              text: content,
            },
          ],
        };
      }
    }

    throw new Error(`Resource not found: ${uri}`);
  });

  // handler: "what tools do you have?"
  // tools are functions AI can call (analyze, search, etc)
  // each has a name, description, and input schema
  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: [
      {
        name: 'reporose_analyze',
        description: 'Scan and analyze a repository, generating map.json',
        inputSchema: {
          type: 'object',
          properties: {
            path: { type: 'string', description: 'Repository path (default: cwd)' },
            reset: { type: 'boolean', description: 'Clear cache and re-analyze' },
          },
        },
      },
      {
        name: 'reporose_get_map',
        description: 'Get the current map.json for a repository',
        inputSchema: {
          type: 'object',
          properties: {
            path: { type: 'string', description: 'Repository path (default: cwd)' },
          },
        },
      },
      {
        name: 'reporose_search_files',
        description: 'Search files by path or description',
        inputSchema: {
          type: 'object',
          properties: {
            path: { type: 'string', description: 'Repository path (default: cwd)' },
            query: { type: 'string', description: 'Search query' },
            limit: { type: 'number', description: 'Max results (default: 10)' },
          },
          required: ['query'],
        },
      },
      {
        name: 'reporose_get_file',
        description: 'Get detailed info about a specific file',
        inputSchema: {
          type: 'object',
          properties: {
            path: { type: 'string', description: 'Repository path (default: cwd)' },
            file: { type: 'string', description: 'File path' },
          },
          required: ['file'],
        },
      },
      {
        name: 'reporose_get_dependencies',
        description: 'Get direct and transitive dependencies for a file',
        inputSchema: {
          type: 'object',
          properties: {
            path: { type: 'string', description: 'Repository path (default: cwd)' },
            file: { type: 'string', description: 'File path' },
            depth: { type: 'number', description: 'Depth (default: 2, max: 3)' },
          },
          required: ['file'],
        },
      },
    ],
  }));

  // handler: "call this tool with these arguments"
  // the big switch statement that actually does the work
  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const tool = request.params.name;
    const args = request.params.arguments || {};
    const target = path.resolve(args.path || repoPath || process.cwd());

    // dispatch to the right tool based on name
    switch (tool) {
      // runs a fresh scan + map, saves to map.json
      case 'reporose_analyze': {
        const result = await scan(target, { silent: true });
        mapDependencies(result);
        const outPath = path.join(target, outDir, 'map.json');
        fs.mkdirSync(path.dirname(outPath), { recursive: true });
        fs.writeFileSync(outPath, JSON.stringify(result, null, 2));
        return {
          content: [
            {
              type: 'text',
              text: `Analyzed ${result.metadata.files_analyzed} files. Map saved to ${outPath}`,
            },
          ],
        };
      }

      // returns the current map.json content
      case 'reporose_get_map': {
        const mapPath = path.join(target, outDir, 'map.json');
        if (!fs.existsSync(mapPath)) {
          return {
            content: [{ type: 'text', text: 'No map.json found. Run reporose_analyze first.' }],
            isError: true,
          };
        }
        const content = fs.readFileSync(mapPath, 'utf8');
        return {
          content: [{ type: 'text', text: content }],
        };
      }

      // searches files by path, description, or tags
      // returns matching files up to the limit
      case 'reporose_search_files': {
        const mapPath = path.join(target, outDir, 'map.json');
        if (!fs.existsSync(mapPath)) {
          return {
            content: [{ type: 'text', text: 'No map.json found. Run reporose_analyze first.' }],
            isError: true,
          };
        }
        const m = JSON.parse(fs.readFileSync(mapPath, 'utf8'));
        const query = (args.query || '').toLowerCase();
        const limit = args.limit || 10;

        const matches = m.files
          .filter(f =>
            f.path.toLowerCase().includes(query) ||
            (f.description && f.description.toLowerCase().includes(query)) ||
            (f.tags && f.tags.some(t => t.includes(query)))
          )
          .slice(0, limit)
          .map(f => ({
            path: f.path,
            description: f.description || '',
            tags: f.tags || [],
          }));

        return {
          content: [{ type: 'text', text: JSON.stringify(matches, null, 2) }],
        };
      }

      // gets detailed info about a specific file by path
      case 'reporose_get_file': {
        const mapPath = path.join(target, outDir, 'map.json');
        if (!fs.existsSync(mapPath)) {
          return {
            content: [{ type: 'text', text: 'No map.json found. Run reporose_analyze first.' }],
            isError: true,
          };
        }
        const m = JSON.parse(fs.readFileSync(mapPath, 'utf8'));
        const filePath = args.file;
        const file = m.files.find(f => f.path === filePath);

        if (!file) {
          return {
            content: [{ type: 'text', text: `File not found: ${filePath}` }],
            isError: true,
          };
        }

        return {
          content: [{ type: 'text', text: JSON.stringify(file, null, 2) }],
        };
      }

      // gets imports and imported_by for a file
      // shows both direct and transitive dependencies
      case 'reporose_get_dependencies': {
        const mapPath = path.join(target, outDir, 'map.json');
        if (!fs.existsSync(mapPath)) {
          return {
            content: [{ type: 'text', text: 'No map.json found. Run reporose_analyze first.' }],
            isError: true,
          };
        }
        const m = JSON.parse(fs.readFileSync(mapPath, 'utf8'));
        const filePath = args.file;
        const depth = Math.min(args.depth || 2, 3);

        const file = m.files.find(f => f.path === filePath);
        if (!file) {
          return {
            content: [{ type: 'text', text: `File not found: ${filePath}` }],
            isError: true,
          };
        }

        const result = {
          path: filePath,
          direct_imports: file.imports || [],
          direct_imported_by: m.files
            .filter(f => (f.imports || []).some(i => i.source === filePath))
            .map(f => f.path),
          transitive_imports: file.transitive_imports || [],
          transitive_imported_by: file.transitive_imported_by || [],
        };

        return {
          content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
        };
      }

      default:
        throw new Error(`Unknown tool: ${tool}`);
    }
  });

  // connect to transport and start listening
  // uses stdin/stdout for communication (thats how MCP works)
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

module.exports = { startMcpServer };
